import { getUniqueEventKey } from "./getUniqueKey.ts";
import type { ProcessedTrace } from "./ProcessedTrace.ts";
import type { ProcessedTraceEvent } from "./ProcessedTraceEvent.ts";
import type { TraceEvent } from "./TraceEvent.ts";

const IGNORED_EVENT_PH = new Set(["M", "f", "s"]);

const IGNORED_EVENT_NAMES = new Set([
  "Activation",
  "Active",
  "Agent::ReportChildTargets",
  "Agent::ReportChildTargetsImpl",
  "Animation",
  "AnimationFrame",
  "AnimationFrame::Presentation",
  "AnimationFrame::Render",
  "AnimationFrame::Script::Compile",
  "AnimationFrame::Script::Execute",
  "AnimationFrame::StyleAndLayout",
  "AnimationHost::TickAnimations",
  "AnyPageLoading",
  "AsyncStackTrace::capture",
  "AsyncTask Run",
  "AsyncTask Scheduled",
  "AttachPage",
  "BEST_EFFORT",
  "BackForwardCacheBufferLimitTracker::DidRemoveFrameOrWorkerFromBackForwardCache",
  "BackgroundProcessor::MaybeStartProcessingResponse",
  "BackgroundProcessor::OnDataPipeReadable",
  "BackgroundProcessor::OnFinishCodeCacheConsumerScriptDecode",
  "BackgroundProcessor::OnFinishStreaming",
  "BackgroundProcessor::RunScriptStreamingTask",
  "BackgroundProcessor::TryStartStreamingTask",
  "BeginImplFrameToSendBeginMainFrame",
  "Blink.ForcedStyleAndLayout.UpdateTime",
  "Blink.Layout.UpdateTime",
  "Blink.Style.UpdateTime",
  "BlinkScheduler_OnTaskCompleted",
  "BlinkScheduler_PerformMicrotaskCheckpoint",
  "BlinkTaskState",
  "BlobRegistry::Register",
  "BufferAvailableToBufferReady",
  "BufferReadyToLatch",
  "ClassicPendingScript::GetSource",
  "ClearStringTableJob started",
  "ClearTrivialWeakRefJob started",
  "ClearWeaknessProcessor start",
  "Closed mojo endpoint",
  "CommandBuffer::OrderingBarrier",
  "CommandBufferHelper::Flush",
  "CommandBufferProxyImpl::Flush",
  "CommandBufferProxyImpl::Initialize",
  "Commit",
  "CommitLoad",
  "CommitToDidCommit",
  "CompressionStream Deflate",
  "ComputeWeaknessProcessor start",
  "ConcurrentMarking::RunMajor Preempted",
  "ContentSettingsManager::AllowStorageAccess",
  "ContentSettingsManager::AllowStorageAccess",
  "ContextCreatedNotification",
  "CookieJar::Cookies",
  "CookieJar::SetCookie",
  "CppGC.AtomicMark",
  "CppGC.AtomicMark",
  "CppGC.AtomicSweep",
  "CppGC.AtomicWeak",
  "CppGC.ConcurrentMark",
  "CppGC.ConcurrentSweep",
  "CppGC.ConcurrentWeakCallback",
  "CppGC.CustomCallbacksProcessing",
  "CppGC.IncrementalMark",
  "CppGC.IncrementalSweep",
  "CppGC.MarkAtomicEpilogue",
  "CppGC.MarkAtomicPrologue",
  "CppGC.MarkFlushEphemerons",
  "CppGC.MarkIncrementalStart",
  "CppGC.MarkOnAllocation",
  "CppGC.MarkTransitiveClosure",
  "CppGC.MarkTransitiveClosure",
  "CppGC.MarkTransitiveClosureWithDeadline",
  "CppGC.MarkTransitiveClosureWithDeadline",
  "CppGC.MarkVisitRoots",
  "CppGC.SweepInLowPriorityTask",
  "CppGC.SweepInTask",
  "CppGC.SweepInvokePreFinalizers",
  "CppGC.WeakContainerCallbacksProcessing",
  "CreateChildProxies",
  "CreateFrame",
  "CreateView",
  "DOMWindow::DoPostMessage",
  "Decode Image",
  "Decode LazyPixelRef",
  "DecodedDataDocumentParser::AppendBytes",
  "DevToolsSession::DispatchProtocolCommand",
  "DevToolsSession::DispatchProtocolCommandImpl",
  "DevToolsSession::SendProtocolResponse",
  "DidFinishRunningAllTilesTask::RunOnWorkerThread",
  "DidNotSubmitInLastFrame",
  "Document::BeginLifecycleUpdatesIfRenderingReady",
  "Document::CancelParsing",
  "Document::DispatchUnloadEvents",
  "Document::Document",
  "Document::FinishedParsing",
  "Document::Initialize",
  "Document::OpenForNavigation",
  "Document::SetReadyState",
  "Document::SetURL",
  "Document::UpdateStyleAndLayout",
  "Document::rebuildLayoutTree",
  "Document::recalcStyle",
  "Document::shutdown",
  "Document::updateActiveStyle",
  "Document::updateStyle",
  "DocumentLoader::BodyDataReceivedImpl",
  "DocumentLoader::BodyLoadingFinished",
  "DocumentLoader::CommitData",
  "DocumentLoader::CommitNavigation",
  "DocumentLoader::CreateParserPostCommit",
  "DocumentLoader::DidCommitNavigation",
  "DocumentLoader::DidInstallNewDocument",
  "DocumentLoader::DocumentLoader",
  "DocumentLoader::FinishedLoading",
  "DocumentLoader::HandleData",
  "DocumentLoader::InitializeWindow",
  "DocumentLoader::RecordUseCountersForCommit",
  "DocumentLoader::StartLoadingResponse",
  "DocumentLoader::~DocumentLoader",
  "EndActivateToSubmitCompositorFrame",
  "EndCommitToActivation",
  "EventDispatch",
  "External javascript injected",
  "ExternalBeginFrameSource::OnBeginFrame",
  "FilterNonTrivialWeakRefJob started",
  "FontCache::PurgeFallbackListShaperCache",
  "Frame::Detach",
  "Frame::SwapImpl",
  "Frame::SwapImpl.CloneState",
  "FrameLoader",
  "FrameLoader::CommitDocumentLoader",
  "FrameLoader::CommitNavigation",
  "FrameLoader::DetachDocument",
  "FrameLoader::DispatchUnloadEventAndFillOldDocInfo",
  "GpuChannel::CreateCommandBuffer",
  "GpuChannel::Flush",
  "GpuChannelHost::CreateViewCommandBuffer",
  "Graphics.Pipeline",
  "HTMLDocumentParser::AttemptToEnd",
  "HTMLDocumentParser::DeferredPumpTokenizerIfPossible",
  "HTMLDocumentParser::DispatchLinkHeaderPreloads",
  "HTMLDocumentParser::DocumentElementAvailable",
  "HTMLDocumentParser::FinishAppend",
  "HTMLDocumentParser::Flush",
  "HTMLDocumentParser::HTMLDocumentParser",
  "HTMLDocumentParser::MaybeFetchQueuedPreloads",
  "HTMLDocumentParser::NotifyScriptLoaded",
  "HTMLDocumentParser::PrepareToStopParsing",
  "HTMLDocumentParser::PumpTokenizer",
  "HTMLDocumentParser::PumpTokenizerIfPossible",
  "HTMLDocumentParser::RunScriptsForPausedTreeBuilder",
  "HTMLDocumentParser::ScanAndPreload",
  "HTMLDocumentParser::SchedulePumpTokenizer",
  "HTMLDocumentParser::append",
  "HTMLDocumentParser::appendBytes",
  "HTMLDocumentParser::~HTMLDocumentParser",
  "HTMLDocumentParser::~HTMLDocumentParser",
  "HTMLParserScriptRunner ExecuteScript",
  "HTMLParserScriptRunner::execute",
  "HTMLParserScriptRunner::executeScriptsWaitingForParsing",
  "HTMLParserScriptRunner::executeScriptsWaitingForParsing",
  "HTMLPreloadScanner::AppendToEnd",
  "HTMLPreloadScanner::HTMLPreloadScanner",
  "HTMLPreloadScanner::scan",
  "HTMLPreloadScanner::~HTMLPreloadScanner",
  "HandlePostMessage",
  "Hidden",
  "HitTest",
  "IDBCursor::continue",
  "IDBCursor::continueRequestSetup",
  "IDBCursor::updateRequestSetup",
  "IDBDatabase::TransactionCreated",
  "IDBDatabase::transaction",
  "IDBFactory::open",
  "IDBIndex::count",
  "IDBIndex::countRequestSetup",
  "IDBIndex::openCursor",
  "IDBIndex::openCursorRequestSetup",
  "IDBObjectStore::add",
  "IDBObjectStore::addRequestSetup",
  "IDBObjectStore::delete",
  "IDBObjectStore::deleteRequestSetup",
  "IDBObjectStore::index",
  "IDBObjectStore::update",
  "IDBOpenDBRequest::onSuccess(database)",
  "IDBRequest::SendResult",
  "IDBRequest::dispatchEvent",
  "IDBTransaction::dispatchEvent",
  "IDBTransaction::onComplete",
  "ImageDecodeTask",
  "ImageResourceContent::updateImage",
  "ImageUploadTask",
  "ImplementationBase::Initialize",
  "InstallConditionalFeatures",
  "JavaScript network request received Cache-Control: no-store resource",
  "Job.WaitForParticipationOpportunity",
  "LargestImagePaint::Candidate",
  "LargestImagePaint::NoCandidate",
  "LargestTextPaint::Candidate",
  "LatchToSwapEnd",
  "LayerTreeHost::SetLayerTreeFrameSink",
  "LayerTreeHostImpl::DidNotProduceFrame",
  "LayerTreeHostImpl::InitializeFrameSink",
  "LayerTreeHostImpl::ReleaseLayerTreeFrameSink",
  "LayerTreeHostImpl::SetVisible",
  "LayerTreeHostSize",
  "LocalDOMWindow::DispatchMessageEventWithOriginCheck",
  "LocalDOMWindow::FrameDestroyed",
  "LocalFrame",
  "LocalFrame::DetachImpl",
  "LocalFrame::PostMessageEvent",
  "LocalFrame::SwapIn",
  "LocalFrameView::BeginLifecycleUpdates",
  "LocalFrameView::HandleLoadCompleted",
  "LocalFrameView::ScheduleAnimation",
  "LocalFrameView::UpdateStyleAndLayout",
  "LocalFrameView::layout",
  "LocalFrameView::performPostLayoutTasks",
  "LocalWindowProxy::CreateContext",
  "LocalWindowProxy::Initialize",
  "LocalWindowProxy::SetupWindowPrototypeChain",
  "LocalWindowProxy::UpdateDocumentProperty",
  "LongIdlePeriodPaused",
  "LongTaskTracker",
  "MainThreadSchedulerIdlePeriod",
  "Major concurrent marking rescheduled",
  "Major concurrent marking started",
  "MemoryCache::evict",
  "ModuleEvaluated",
  "MojoURLLoaderClient::OnReceiveResponse",
  "NativeExtensionBindingsSystem::SendRequest",
  "NavigationBodyLoader::OnReadable",
  "NavigationBodyLoader::ReadFromDataPipe",
  "NavigationBodyLoader::StartLoadingBody",
  "NeedsBeginFrames",
  "Not Visible",
  "PageAnimator::serviceScriptedAnimations",
  "PageEvacuationJob started",
  "Parallel scavenge started",
  "PendingCommit",
  "PendingScript::ExecuteScriptBlock",
  "PeriodicPurge",
  "PipelineReporter",
  "PointersUpdatingJob started",
  "ProxyImpl::InitializeLayerTreeFrameSinkOnImplThread",
  "ProxyImpl::OnCanDrawStateChanged",
  "ProxyImpl::ScheduledActionBeginLayerTreeFrameSinkCreation",
  "ProxyImpl::ScheduledActionPrepareTiles",
  "ProxyImpl::SetVisibleOnImplThread",
  "ProxyMain::DidInitializeLayerTreeFrameSink",
  "ProxyMain::RequestNewLayerTreeFrameSink",
  "ProxyMain::SetVisible",
  "RasterImplementation::Initialize",
  "RasterImplementation::SetAggressivelyFreeResources",
  "RasterImplementation::SetAggressivelyFreeResources",
  "RasterTask",
  "Receive mojo message",
  "Receive mojo reply",
  "ReceiveCompositorFrameToStartDraw",
  "RemoteFrame",
  "RemoteFrame::DidSetFramePolicyHeaders",
  "RemoteFrame::DidStopLoading",
  "RemoteFrame::EnforceInsecureNavigationsSet",
  "RemoteFrame::SetFrameOwnerProperties",
  "RemoteFrame::SetHadStickyUserActivationBeforeNavigation",
  "RemoteFrame::SetReplicatedOrigin",
  "RemoteFrame::SetReplicatedOrigin",
  "RemoteWindowProxy::Initialize",
  "RenderFrameHostImpl",
  "RenderFrameImpl::CommitNavigation",
  "RenderFrameImpl::CommitNavigationWithParams",
  "RenderFrameImpl::DidClearWindowObject",
  "RenderFrameImpl::DidCommitNavigation",
  "RenderFrameImpl::DidCreateScriptContext",
  "RenderFrameImpl::DidDispatchDOMContentLoadedEvent",
  "RenderFrameImpl::DidObserveNewFeatureUsage",
  "RenderFrameImpl::NotifyObserversOfNavigationCommit",
  "RenderFrameImpl::SetUpSharedMemoryForDroppedFrames",
  "RenderFrameImpl::didCommitProvisionalLoad",
  "RenderFrameImpl::didFinishLoad",
  "RenderFrameImpl::didFinishSameDocumentNavigation",
  "RenderFrameImpl::didStartLoading",
  "RenderFrameImpl::didStartProvisionalLoad",
  "RenderFrameImpl::didStopLoading",
  "RenderThreadImpl::EstablishGpuChannel",
  "Renderer Navigation",
  "Resource::appendData",
  "ResourceFetcher::requestResource",
  "ResourceLoadPriorityOptimizer::UpdateImagePrioritiesAndSpeculativeDecodes",
  "ResourceRequestSender::OnReceivedResponse",
  "ResourceRequestSender::OnRequestComplete",
  "ResponseBodyLoader::DidFinishLoadingBody",
  "RestrictedCookieManager::GetCookiesString",
  "RunMicrotasks",
  "RunPendingMicrotask",
  "RunTask",
  "ScheduledTasks",
  "ScheduledTasksState",
  "Scheduler::BeginFrame",
  "Scheduler::BeginImplFrame",
  "Scheduler::DidCreateAndInitializeLayerTreeFrameSink",
  "Scheduler::OnBeginImplFrameDeadline",
  "Scheduler::ScheduleBeginImplFrameDeadline",
  "Scheduler::SetDeferBeginMainFrame",
  "SchedulerStateMachine::SetNeedsPrepareTiles",
  "ScopedAllowBaseSyncPrimitivesOutsideBlockingScope",
  "ScopedBlockingCall",
  "ScopedBlockingCallWithBaseSyncPrimitives",
  "ScriptCatchup",
  "ScriptInjection",
  "ScriptInjection::InjectJs",
  "ScriptRunner::ExecutePendingScript",
  "SendBeginMainFrameToCommit",
  "SequenceManager::DoIdleWork",
  "SequenceManagerImpl::MaybeReclaimMemory",
  "SerializedScriptValueFactory::create",
  "SerializedScriptValueFactory::create",
  "SerializedScriptValueFactory::deserialize",
  "SimpleWatcher::OnHandleReady",
  "Speculative",
  "StartDrawToSwapStart",
  "StubScriptCatchup",
  "StyleEngine::clearResolver",
  "StyleEngine::updateActiveStyleSheets",
  "SubmitCompositorFrameToPresentationCompositorFrame",
  "SubmitToReceiveCompositorFrame",
  "SwapEndToPresentationCompositorFrame",
  "TaskQueueThrottler::OnNextWakeUpChanged",
  "TaskQueueThrottler::OnNextWakeUpChanged",
  "TaskSetFinishedTaskImpl::RunOnWorkerThread",
  "TextResourceDecoder::Decode",
  "ThreadController active",
  "ThreadControllerImpl::RunTask",
  "ThreadPool_RunTask",
  "ThrottlingURLLoader::OnReceiveResponse",
  "ThrottlingURLLoader::Start",
  "ThrottlingURLLoader::StartNow",
  "ThrottlingURLLoader::ThrottlingURLLoader",
  "ThrottlingURLLoader::~ThrottlingURLLoader",
  "TileManager::AssignGpuMemoryToTiles",
  "TileManager::CheckForCompletedTasksAndIssueSignals",
  "TileManager::CheckPendingGpuWorkAndIssueSignals",
  "TileManager::DidFinishRunningAllTileTaskRemoteFrames",
  "TileManager::DidFinishRunningAllTileTasks",
  "TileManager::DidFinishRunningTileTasksRequiredForActivation",
  "TileManager::DidFinishRunningTileTasksRequiredForDraw",
  "TileManager::PrepareTiles",
  "TileManager::ScheduleTasks",
  "TileTaskManagerImpl::CheckForCompletedTasks",
  "TileTaskManagerImpl::ScheduleTasks",
  "TimerBase::run",
  "TransferBuffer::Free",
  "URLLoader::Context::Cancel",
  "URLLoader::Context::OnCompletedRequest",
  "URLLoader::Context::OnReceivedResponse",
  "URLLoader::Context::Start",
  "URLLoader::loadAsynchronously",
  "USER_BLOCKING",
  "USER_VISIBLE",
  "Unknown",
  "UpdateLayer",
  "User blocking",
  "User visible",
  "UserTiming::Measure",
  "V8.BytecodeBudgetInterrupt",
  "V8.BytecodeBudgetInterruptWithStackCheck",
  "V8.DeoptimizeAllOptimizedCodeWithFunction",
  "V8.DeoptimizeCode",
  "V8.DeserializeContext",
  "V8.DeserializeIsolate",
  "V8.GCFinalizeMC",
  "V8.GCFinalizeMCReduceMemory",
  "V8.GCIncrementalMarking",
  "V8.GCIncrementalMarking",
  "V8.GCIncrementalMarkingStart",
  "V8.GCPhantomHandleProcessingCallback",
  "V8.GCScavenger",
  "V8.GC_BACKGROUND_FULL_ARRAY_BUFFER_SWEEP",
  "V8.GC_BACKGROUND_SAFEPOINT",
  "V8.GC_BACKGROUND_UNPARK",
  "V8.GC_BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP",
  "V8.GC_CONSERVATIVE_STACK_SCANNING",
  "V8.GC_FULL_ARRAY_BUFFER_SWEEP",
  "V8.GC_HEAP_EMBEDDER_TRACING_EPILOGUE",
  "V8.GC_HEAP_EPILOGUE",
  "V8.GC_HEAP_EPILOGUE_SAFEPOINT",
  "V8.GC_HEAP_EXTERNAL_EPILOGUE",
  "V8.GC_HEAP_EXTERNAL_PROLOGUE",
  "V8.GC_HEAP_EXTERNAL_SECOND_PASS_CALLBACKS",
  "V8.GC_HEAP_EXTERNAL_WEAK_GLOBAL_HANDLES",
  "V8.GC_HEAP_PROLOGUE",
  "V8.GC_HEAP_PROLOGUE_SAFEPOINT",
  "V8.GC_MARK_COMPACTOR",
  "V8.GC_MC_BACKGROUND_EVACUATE_COPY",
  "V8.GC_MC_BACKGROUND_EVACUATE_UPDATE_POINTERS",
  "V8.GC_MC_BACKGROUND_MARKING",
  "V8.GC_MC_BACKGROUND_MARKING",
  "V8.GC_MC_BACKGROUND_SWEEPING",
  "V8.GC_MC_CLEAR",
  "V8.GC_MC_CLEAR_EXTERNAL_STRING_TABLE",
  "V8.GC_MC_CLEAR_FLUSHABLE_BYTECODE",
  "V8.GC_MC_CLEAR_FLUSHED_JS_FUNCTIONS",
  "V8.GC_MC_CLEAR_JOIN_JOB",
  "V8.GC_MC_CLEAR_JS_WEAK_REFERENCES",
  "V8.GC_MC_CLEAR_MAPS",
  "V8.GC_MC_CLEAR_STRING_FORWARDING_TABLE",
  "V8.GC_MC_CLEAR_STRING_TABLE",
  "V8.GC_MC_CLEAR_WEAK_COLLECTIONS",
  "V8.GC_MC_CLEAR_WEAK_GLOBAL_HANDLES",
  "V8.GC_MC_CLEAR_WEAK_LISTS",
  "V8.GC_MC_CLEAR_WEAK_REFERENCES_FILTER_NON_TRIVIAL",
  "V8.GC_MC_CLEAR_WEAK_REFERENCES_JOIN_FILTER_JOB",
  "V8.GC_MC_CLEAR_WEAK_REFERENCES_NON_TRIVIAL",
  "V8.GC_MC_CLEAR_WEAK_REFERENCES_TRIVIAL",
  "V8.GC_MC_COMPLETE_SWEEPING",
  "V8.GC_MC_COMPLETE_SWEEP_ARRAY_BUFFERS",
  "V8.GC_MC_EPILOGUE",
  "V8.GC_MC_EVACUATE",
  "V8.GC_MC_EVACUATE_CLEAN_UP",
  "V8.GC_MC_EVACUATE_COPY",
  "V8.GC_MC_EVACUATE_COPY_PARALLEL",
  "V8.GC_MC_EVACUATE_EPILOGUE",
  "V8.GC_MC_EVACUATE_PROLOGUE",
  "V8.GC_MC_EVACUATE_REBALANCE",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_CLIENT_HEAPS",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_PARALLEL",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_POINTER_TABLES",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_SLOTS_MAIN",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_TO_NEW_ROOTS",
  "V8.GC_MC_EVACUATE_UPDATE_POINTERS_WEAK",
  "V8.GC_MC_FINISH",
  "V8.GC_MC_FINISH_SWEEP_ARRAY_BUFFERS",
  "V8.GC_MC_INCREMENTAL",
  "V8.GC_MC_INCREMENTAL_EMBEDDER_TRACING",
  "V8.GC_MC_INCREMENTAL_EXTERNAL_EPILOGUE",
  "V8.GC_MC_INCREMENTAL_EXTERNAL_PROLOGUE",
  "V8.GC_MC_INCREMENTAL_START",
  "V8.GC_MC_MARK",
  "V8.GC_MC_MARK_CLIENT_HEAPS",
  "V8.GC_MC_MARK_EMBEDDER_PROLOGUE",
  "V8.GC_MC_MARK_EMBEDDER_TRACING",
  "V8.GC_MC_MARK_FINISH_INCREMENTAL",
  "V8.GC_MC_MARK_FULL_CLOSURE_PARALLEL",
  "V8.GC_MC_MARK_FULL_CLOSURE_PARALLEL_JOIN",
  "V8.GC_MC_MARK_FULL_CLOSURE_SERIAL",
  "V8.GC_MC_MARK_RETAIN_MAPS",
  "V8.GC_MC_MARK_ROOTS",
  "V8.GC_MC_MARK_WEAK_CLOSURE_EPHEMERON_LINEAR",
  "V8.GC_MC_MARK_WEAK_CLOSURE_EPHEMERON_MARKING",
  "V8.GC_MC_PROLOGUE",
  "V8.GC_MC_SWEEP",
  "V8.GC_MC_SWEEP_CODE_POINTER_TABLE",
  "V8.GC_MC_SWEEP_EXTERNAL_POINTER_TABLE",
  "V8.GC_MC_SWEEP_JS_DISPATCH_TABLE",
  "V8.GC_MC_SWEEP_NEW_LO",
  "V8.GC_MC_SWEEP_START_JOBS",
  "V8.GC_MC_SWEEP_TRUSTED_POINTER_TABLE",
  "V8.GC_MC_SWEEP_WASM_CODE_POINTER_TABLE",
  "V8.GC_MC_WEAKNESS_HANDLING",
  "V8.GC_MINOR_MS_BACKGROUND_SWEEPING",
  "V8.GC_MINOR_MS_SWEEP",
  "V8.GC_SCAVENGER",
  "V8.GC_SCAVENGER_BACKGROUND_SCAVENGE_PARALLEL",
  "V8.GC_SCAVENGER_BACKGROUND_TRACED_HANDLES_COMPUTE_WEAKNESS_PARALLEL",
  "V8.GC_SCAVENGER_BACKGROUND_TRACED_HANDLES_RESET_PARALLEL",
  "V8.GC_SCAVENGER_COMPLETE_SWEEP_ARRAY_BUFFERS",
  "V8.GC_SCAVENGER_FREE_REMEMBERED_SET",
  "V8.GC_SCAVENGER_RESIZE_NEW_SPACE",
  "V8.GC_SCAVENGER_SCAVENGE",
  "V8.GC_SCAVENGER_SCAVENGE_FINALIZE",
  "V8.GC_SCAVENGER_SCAVENGE_PARALLEL",
  "V8.GC_SCAVENGER_SCAVENGE_PARALLEL_PHASE",
  "V8.GC_SCAVENGER_SCAVENGE_RESTORE_AND_QUARANTINE_PINNED",
  "V8.GC_SCAVENGER_SCAVENGE_ROOTS",
  "V8.GC_SCAVENGER_SCAVENGE_UPDATE_REFS",
  "V8.GC_SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_IDENTIFY",
  "V8.GC_SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_PROCESS",
  "V8.GC_SCAVENGER_SWEEP_ARRAY_BUFFERS",
  "V8.GC_SCAVENGER_TRACED_HANDLES_COMPUTE_WEAKNESS_PARALLEL",
  "V8.GC_SCAVENGER_TRACED_HANDLES_RESET_PARALLEL",
  "V8.GC_TIME_TO_SAFEPOINT",
  "V8.GC_YOUNG_ARRAY_BUFFER_SWEEP",
  "V8.HandleInterrupts",
  "V8.InvokeApiInterruptCallbacks",
  "V8.StackGuard",
  "V8PerIsolateData::Initialize",
  "V8RuntimeAgentImpl::enable",
  "V8StackTraceImpl::capture",
  "Visible",
  "VisiblePageLoading",
  "VisualViewport::setSize",
  "WebLocalFrameImpl::createFrameView",
  "WebSocket live connection",
  "WebSocket used in the page with Cache-Control: no store",
  "WidgetBase::UpdateScreenRects",
  "WidgetBase::UpdateVisualProperties",
  "WidgetBase::WasHidden",
  "WidgetBase::WasShown",
  "WorkerThread active",
  "X509Certificate::CreateFromDERCertChain",
  "XHRLoad",
  "XHRReadyStateChange",
  "YieldParserForScriptLoad",
  "api_call",
  "cc::TaskGraphWorkQueue::ScheduleTasks",
  "commitNavigationEnd",
  "document loaded",
  "domContentLoadedEventEnd",
  "domContentLoadedEventStart",
  "domLoading",
  "fetchStart",
  "firstMeaningfulPaintCandidate",
  "largestContentfulPaint::Candidate",
  "layerId",
  "loadEventEnd",
  "loadEventStart",
  "no",
  "none",
  "rendering_starved",
  "responseEnd",
  "silent",
  "subresource has Cache-Control: No-Store",
  "toFramesVector",
  "unloadEventEnd",
  "unloadEventStart",
  "v8.callAsConstructor",
  "v8.callFunction",
  "v8.deserializeOnBackground",
  "v8.deserializeOnBackground.finishedBeforeResource",
  "v8.deserializeOnBackground.start",
  "v8.evaluateModule",
  "v8.newInstance",
  "v8.parseOnBackground",
  "v8.parseOnBackgroundParsing",
  "v8.parseOnBackgroundWaiting",
  "v8.produceCache",
  "v8.produceModuleCache",
  "v8::Debugger::AsyncTaskCanceled",
  "v8::Debugger::AsyncTaskRun",
  "v8::Debugger::AsyncTaskScheduled",
  "very_high",
  "FrameStartedLoading",
  "UpdateCounters",
  "NeedsBeginFrameChanged",
  "ResourceSendRequest",
  "ResourceReceiveResponse",
  "RendererNavigationMetricsManager::RecordTraceEventsAndMetrics",
  "ResourceReceivedData",
  "ResourceMarkAsCached",
  "ResourceFinish",
  "LinkPreconnect",
  "BeginFrame",
  "RequestMainThreadFrame",
  "ParseMetaViewport",
  "BeginMainThreadFrame",
  "SetLayerTreeId",
  "DOMStats",
  "PaintTimingVisualizer::Viewport",
  "BeginCommitCompositorFrame",
  "ActivateLayerTree",
  "DrawFrame",
  "BenchmarkInstrumentation::ImplThreadRenderingStats",
  "PaintTimingVisualizer::LayoutObjectPainted",
  "Draw LazyPixelRef",
  "MarkLoad",
  "MarkDOMContent",
  "LayoutImageUnsized",
  "viewport",
  "TracingSessionIdForWorker",
  "WebSocketCreate",
  "WebSocketSendHandshakeRequest",
  "LoadFinished",
  "WebSocketReceiveHandshakeResponse",
  "WebSocketSend",
  "WebSocketReceive",
]);

const MAIN_THREAD_NAME = "CrRendererMain";

export function processTrace(traceEvents: TraceEvent[]): ProcessedTrace {
  let mainThreadPID = null;
  for (const evt of traceEvents) {
    if (evt.args?.name === MAIN_THREAD_NAME) {
      mainThreadPID = evt.pid;
    }
  }

  let seenStartProfile = false;
  const groupedTraceEvents: Record<string, ProcessedTraceEvent> = {};
  const filteredTraceEvents: Array<TraceEvent> = [];
  for (const evt of traceEvents) {
    if (evt.name.startsWith("URL:") && evt.cat === "navigation") {
      continue;
    }

    if (evt.name.startsWith("react-")) {
      continue;
    }

    if (evt.name.startsWith("auto cc::")) {
      continue;
    }

    if (evt.name === "CpuProfiler::StartProfiling") {
      seenStartProfile = true;
      continue;
    }

    if (!seenStartProfile) {
      continue;
    }

    if (IGNORED_EVENT_PH.has(evt.ph)) {
      continue;
    }

    if (IGNORED_EVENT_NAMES.has(evt.name)) {
      continue;
    }

    if (evt.pid !== mainThreadPID) {
      continue;
    }

    const id = getUniqueEventKey(evt);
    if (!id) {
      console.log(evt);
      continue;
    }

    filteredTraceEvents.push(evt);

    groupedTraceEvents[id] = groupedTraceEvents[id] ?? {
      id,
      name: evt.name,
      originalEvents: [],
    };
    groupedTraceEvents[id].originalEvents.push(evt);
  }

  return {
    grouped: groupedTraceEvents,
    filtered: filteredTraceEvents,
  };
}
